# This is a basic workflow to help you get started with Actions

name: CI Run Playwright Automated Login Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  # or you can change to windows-latest
   
    # Define your desired browsers
   # strategy:
    #  matrix:
     #   browser: [chromium, firefox, webkit]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository/code
        uses: actions/checkout@v5

      # Set up Node.js......
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*' # Or a specific Node.js version
          
      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers and their dependencies
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Executes the project's test suite
      - name: Run Playwright tests
        run: npx playwright test


     # Run tests in mulptiple browsers
     # - name: Run Playwright tests
     #   run: npx playwright test --project=${{ matrix.browser }}
