name: CI Run NUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or windows-latest, if your project requires it

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0' # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

   # Install Playwright browsers and their dependencies
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build project
      run: dotnet build --no-restore

    - name: Run NUnit tests
      run: dotnet test --no-build --verbosity normal
