name: CI Run NUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or windows-latest, if your project requires it

    steps:
 # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: Echo GITHUB_ACTION_PATH
      run: echo "The GitHub Action path is:$GITHUB_ACTION_PATH"
      #run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0' # Specify your .NET version

    - name: Restore .NET dependencies
      run: dotnet restore
      
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Initialize Node.js dependencies
      run: npm init --yes

    - name: Install Node.js dependencies
      run: npm ci

    - name: Install @playwright/test
      run: npm install @playwright/test

      
 # TRY: Install Ensure PowerShell is functional and updated:
    - name: Ensure PowerShell is functional and updated 
      run: dotnet tool install --global PowerShell 
      
  # TRY: Correctly use the Playwright CLI for installation
    - name: Use Playwright CLI for installation
      run: dotnet tool install --global Microsoft.Playwright.CLI

 # NPX Install  Playwright browsers and their dependencies
    - name: NPX Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build project
      run: dotnet build --no-restore

  # PWSH Install Playwright browsers and their dependencies
    - name: PWSH Install Playwright browsers
      run: pwsh bin/Debug/net10.0/playwright.ps1 install

    - name: Run NUnit tests
      run: dotnet test --no-build --verbosity normal

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ always() }} # Upload artifact even if the previous step fails
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 # Retain the report for 30 days

