name: CI Run NUnit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or windows-latest, if your project requires it

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0' # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore
      
 # TRY: Install Ensure PowerShell is functional and updated:
    - name: Ensure PowerShell is functional and updated 
      run: dotnet tool install --global PowerShell 
      
  # TRY: Correctly use the Playwright CLI for installation
    - name: Use Playwright CLI for installation
      run: dotnet tool install --global Microsoft.Playwright.CLI
      
 # Install Playwright browsers and their dependencies
    - name: Install Playwright browsers
      run: pwsh bin/Debug/net10.0/playwright.ps1 install --with-deps
      
 # Change the execution policy to allow script execution.
    - name: Change execution policy
      run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
      
    - name: Build project
      run: dotnet build --no-restore

    - name: Run NUnit tests
      run: dotnet test --no-build --verbosity normal
